/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.deluxebooking;

/**
 *
 * @author joshu
 */
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

public class RegisterActivity extends javax.swing.JFrame {

    /**
     * Creates new form LoginActivity
     */
    public RegisterActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deluxebooking = new javax.swing.JLabel();
        createAccountTitle = new javax.swing.JLabel();
        subTtitle = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameRegister = new javax.swing.JTextField();
        lastNameRegister = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailRegister = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        firstNameLabel4 = new javax.swing.JLabel();
        textToLoginActivity = new javax.swing.JLabel();
        passwordRegister = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanel1.setBackground(new java.awt.Color(112, 188, 255));

        deluxebooking.setFont(new java.awt.Font("MuseoModerno ExtraBold", 0, 24)); // NOI18N
        deluxebooking.setForeground(new java.awt.Color(254, 254, 254));
        deluxebooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deluxebooking.setText("deluxe booking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(deluxebooking, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(deluxebooking)
                .addContainerGap(514, Short.MAX_VALUE))
        );

        createAccountTitle.setFont(new java.awt.Font("Inter 18pt Black", 0, 35)); // NOI18N
        createAccountTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        createAccountTitle.setText("Create an account");

        subTtitle.setFont(new java.awt.Font("Inter 24pt", 0, 14)); // NOI18N
        subTtitle.setText("Your Journey Starts Here");

        firstNameLabel.setFont(new java.awt.Font("Inter 18pt Medium", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name");

        firstNameRegister.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        firstNameRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        firstNameRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        firstNameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameRegisterActionPerformed(evt);
            }
        });

        lastNameRegister.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        lastNameRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lastNameRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lastNameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameRegisterActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Inter 18pt Medium", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name");

        emailLabel.setFont(new java.awt.Font("Inter 18pt Medium", 0, 14)); // NOI18N
        emailLabel.setText("Email");

        emailRegister.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        emailRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        emailRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailRegisterActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Inter 18pt Medium", 0, 14)); // NOI18N
        passwordLabel.setText("Password");

        registerBtn.setBackground(new java.awt.Color(112, 188, 255));
        registerBtn.setFont(new java.awt.Font("Inter 24pt SemiBold", 0, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(254, 254, 254));
        registerBtn.setText("Create Account");
        registerBtn.setBorder(null);
        registerBtn.setBorderPainted(false);
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        firstNameLabel4.setFont(new java.awt.Font("Inter 18pt Medium", 0, 14)); // NOI18N
        firstNameLabel4.setText("Already have an account? ");

        textToLoginActivity.setFont(new java.awt.Font("Inter 24pt SemiBold", 0, 14)); // NOI18N
        textToLoginActivity.setForeground(new java.awt.Color(112, 188, 255));
        textToLoginActivity.setText("Log in.");
        textToLoginActivity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textToLoginActivityMouseClicked(evt);
            }
        });

        passwordRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subTtitle)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNameRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(registerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstNameRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstNameLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textToLoginActivity))
                    .addComponent(passwordRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 199, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(635, Short.MAX_VALUE)
                    .addComponent(createAccountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(108, 108, 108)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(subTtitle)
                .addGap(51, 51, 51)
                .addComponent(firstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lastNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addGap(18, 18, 18)
                .addComponent(passwordRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textToLoginActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(createAccountTitle)
                    .addContainerGap(586, Short.MAX_VALUE)))
        );

        createAccountTitle.getAccessibleContext().setAccessibleParent(deluxebooking);
        subTtitle.getAccessibleContext().setAccessibleParent(createAccountTitle);
        firstNameRegister.getAccessibleContext().setAccessibleDescription("");
        firstNameRegister.getAccessibleContext().setAccessibleParent(firstNameLabel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameRegisterActionPerformed

    private void lastNameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameRegisterActionPerformed

    private void emailRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailRegisterActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        SearchFlight searchFlight = new SearchFlight();
        searchFlight.show();
        dispose();
    }//GEN-LAST:event_registerBtnActionPerformed

    private void textToLoginActivityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textToLoginActivityMouseClicked
        // TODO add your handling code here:
        LoginActivity loginactivity = new LoginActivity();
        loginactivity.show();
        dispose();
    }//GEN-LAST:event_textToLoginActivityMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createAccountTitle;
    private javax.swing.JLabel deluxebooking;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailRegister;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel4;
    private javax.swing.JTextField firstNameRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameRegister;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordRegister;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel subTtitle;
    private javax.swing.JLabel textToLoginActivity;
    // End of variables declaration//GEN-END:variables
}
